backend:
  name: github
  repo: leilshop/leil-shop
  branch: main
  site_domain: lively-malabi-821bd8.netlify.app

site_url: "https://leil.shop"
display_url: "https://leil.shop"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "store_data"
    label: "إدارة المخزون والأسعار"
    files:
      - label: "بيانات المنتجات"
        name: "products"
        file: "data.json"
        fields:
          - label: "قائمة المنتجات"
            name: "items"
            widget: "list"
            fields:
              - {label: "اسم المنتج", name: "name", widget: "string"}
              - {label: "الحجم", name: "size", widget: "string"}
              - {label: "السعر", name: "price", widget: "number"}
              - {label: "المخزون المتوفر", name: "stock", widget: "number"}
